/* eslint-disable */
/**
 * Generated by `npm run db:types` from the live public schema.
 * Same source of truth as `supabase gen types typescript --schema public`.
 * Do not edit by hand — regenerate after migrations.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      addresses: {
        Row: {
          id: string
          business_account_id: string | null
          user_id: string | null
          label: string
          line1: string
          line2: string
          city: string
          state: string
          zip: string
          is_default: boolean
        }
        Insert: {
          id?: string
          business_account_id?: string | null
          user_id?: string | null
          label?: string
          line1: string
          line2?: string
          city: string
          state: string
          zip: string
          is_default?: boolean
        }
        Update: {
          id?: string
          business_account_id?: string | null
          user_id?: string | null
          label?: string
          line1?: string
          line2?: string
          city?: string
          state?: string
          zip?: string
          is_default?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "addresses_business_account_id_fkey"
            columns: ["business_account_id"]
            isOneToOne: false
            referencedRelation: "business_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "addresses_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      business_accounts: {
        Row: {
          id: string
          clerk_org_id: string | null
          company_name: string
          billing_address_id: string | null
          tax_exempt: boolean
          account_tier: Database["public"]["Enums"]["account_tier"]
          stripe_customer_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          clerk_org_id?: string | null
          company_name: string
          billing_address_id?: string | null
          tax_exempt?: boolean
          account_tier?: Database["public"]["Enums"]["account_tier"]
          stripe_customer_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          clerk_org_id?: string | null
          company_name?: string
          billing_address_id?: string | null
          tax_exempt?: boolean
          account_tier?: Database["public"]["Enums"]["account_tier"]
          stripe_customer_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "business_accounts_billing_address_fk"
            columns: ["billing_address_id"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
        ]
      }
      cart_items: {
        Row: {
          id: string
          cart_id: string
          product_id: string
          cases: number
        }
        Insert: {
          id?: string
          cart_id: string
          product_id: string
          cases: number
        }
        Update: {
          id?: string
          cart_id?: string
          product_id?: string
          cases?: number
        }
        Relationships: [
          {
            foreignKeyName: "cart_items_cart_id_fkey"
            columns: ["cart_id"]
            isOneToOne: false
            referencedRelation: "carts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cart_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      carts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "carts_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          description: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string
        }
        Relationships: []
      }
      inventory: {
        Row: {
          id: string
          product_id: string
          warehouse_id: string
          quantity_on_hand: number
          low_stock_threshold: number
        }
        Insert: {
          id?: string
          product_id: string
          warehouse_id: string
          quantity_on_hand?: number
          low_stock_threshold?: number
        }
        Update: {
          id?: string
          product_id?: string
          warehouse_id?: string
          quantity_on_hand?: number
          low_stock_threshold?: number
        }
        Relationships: [
          {
            foreignKeyName: "inventory_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          cases: number
          unit_price_cents_at_purchase: number
        }
        Insert: {
          id?: string
          order_id: string
          product_id: string
          cases: number
          unit_price_cents_at_purchase: number
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          cases?: number
          unit_price_cents_at_purchase?: number
        }
        Relationships: [
          {
            foreignKeyName: "order_items_order_id_fkey"
            columns: ["order_id"]
            isOneToOne: false
            referencedRelation: "orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      orders: {
        Row: {
          id: string
          user_id: string
          business_account_id: string | null
          status: Database["public"]["Enums"]["order_status"]
          subtotal_cents: number
          shipping_cents: number
          tax_cents: number
          total_cents: number
          stripe_payment_intent_id: string | null
          delivery_method: string
          shipping_address_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          business_account_id?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          subtotal_cents: number
          shipping_cents: number
          tax_cents: number
          total_cents: number
          stripe_payment_intent_id?: string | null
          delivery_method: string
          shipping_address_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          business_account_id?: string | null
          status?: Database["public"]["Enums"]["order_status"]
          subtotal_cents?: number
          shipping_cents?: number
          tax_cents?: number
          total_cents?: number
          stripe_payment_intent_id?: string | null
          delivery_method?: string
          shipping_address_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "orders_business_account_id_fkey"
            columns: ["business_account_id"]
            isOneToOne: false
            referencedRelation: "business_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_shipping_address_id_fkey"
            columns: ["shipping_address_id"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "orders_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      price_tiers: {
        Row: {
          id: string
          product_id: string
          min_cases: number
          price_per_case_cents: number
        }
        Insert: {
          id?: string
          product_id: string
          min_cases: number
          price_per_case_cents: number
        }
        Update: {
          id?: string
          product_id?: string
          min_cases?: number
          price_per_case_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "price_tiers_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          id: string
          sku: string
          name: string
          category_id: string
          description: string
          image_url: string | null
          pack_size: string
          unit_count: number
          is_active: boolean
        }
        Insert: {
          id?: string
          sku: string
          name: string
          category_id: string
          description?: string
          image_url?: string | null
          pack_size: string
          unit_count?: number
          is_active?: boolean
        }
        Update: {
          id?: string
          sku?: string
          name?: string
          category_id?: string
          description?: string
          image_url?: string | null
          pack_size?: string
          unit_count?: number
          is_active?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      tax_rules: {
        Row: {
          id: string
          state_code: string
          rate_percent: number
        }
        Insert: {
          id?: string
          state_code: string
          rate_percent: number
        }
        Update: {
          id?: string
          state_code?: string
          rate_percent?: number
        }
        Relationships: []
      }
      users: {
        Row: {
          id: string
          clerk_user_id: string
          business_account_id: string | null
          role: Database["public"]["Enums"]["user_role"]
          email: string
          created_at: string
        }
        Insert: {
          id?: string
          clerk_user_id: string
          business_account_id?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          email: string
          created_at?: string
        }
        Update: {
          id?: string
          clerk_user_id?: string
          business_account_id?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          email?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "users_business_account_id_fkey"
            columns: ["business_account_id"]
            isOneToOne: false
            referencedRelation: "business_accounts"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouses: {
        Row: {
          id: string
          name: string
          address_id: string | null
        }
        Insert: {
          id?: string
          name: string
          address_id?: string | null
        }
        Update: {
          id?: string
          name?: string
          address_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "warehouses_address_id_fkey"
            columns: ["address_id"]
            isOneToOne: false
            referencedRelation: "addresses"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      current_app_user: { Args: Record<PropertyKey, never>; Returns: Database["public"]["Tables"]["users"]["Row"] }
      is_admin: { Args: Record<PropertyKey, never>; Returns: boolean }
    }
    Enums: {
      account_tier: "business" | "individual"
      order_status: "pending" | "paid" | "fulfilled" | "cancelled" | "payment_failed"
      user_role: "admin" | "buyer" | "staff"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database[Extract<keyof Database, "public">]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

