import type { Category, Product } from "@/types/commerce";

function tiers(baseCents: number) {
  return [
    { min_cases: 1, price_per_case_cents: baseCents },
    { min_cases: 5, price_per_case_cents: Math.round(baseCents * 0.93) },
    { min_cases: 12, price_per_case_cents: Math.round(baseCents * 0.86) },
  ];
}

export const CATEGORIES: Category[] = [
  { id: "cat_beverages", slug: "beverages", name: "Beverages", description: "Soda, water, and ready-to-drink cases." },
  { id: "cat_snacks", slug: "snacks", name: "Snacks", description: "Chips, nuts, and grab-and-go snacks." },
  { id: "cat_cleaning", slug: "cleaning", name: "Cleaning", description: "Degreasers, sanitizers, and floor care." },
  { id: "cat_paper", slug: "paper", name: "Paper & disposables", description: "Towels, napkins, and tissue." },
  { id: "cat_frozen", slug: "frozen", name: "Frozen", description: "Frozen proteins and sides." },
  { id: "cat_dairy", slug: "dairy", name: "Dairy", description: "Cheese, butter, and cultured dairy." },
  { id: "cat_dry-goods", slug: "dry-goods", name: "Dry goods", description: "Rice, pasta, flour, and pantry staples." },
  { id: "cat_packaging", slug: "packaging", name: "Packaging", description: "Takeout containers, bags, and film." },
  { id: "cat_produce", slug: "produce", name: "Produce", description: "Case-packed fruit and vegetables." },
  { id: "cat_coffee", slug: "coffee", name: "Coffee & tea", description: "Bulk coffee, tea, and creamers." },
];

export const PRODUCTS: Product[] = [
  {
    id: "prd_cola",
    sku: "BEV-COLA-24",
    name: "House Cola 12oz cans",
    category_id: "cat_beverages",
    description: "Classic cola in 24-can cases. Pallet-ready for fountain backup and grab-and-go coolers.",
    image_url: null,
    pack_size: "24 × 12oz",
    unit_count: 24,
    is_active: true,
    price_tiers: tiers(1899),
    quantity_on_hand: 140,
    low_stock_threshold: 24,
  },
  {
    id: "prd_water",
    sku: "BEV-SPARK-24",
    name: "Sparkling water variety",
    category_id: "cat_beverages",
    description: "Unflavored and citrus sparkling water, 24-can mixed case.",
    image_url: null,
    pack_size: "24 × 12oz",
    unit_count: 24,
    is_active: true,
    price_tiers: tiers(1649),
    quantity_on_hand: 96,
    low_stock_threshold: 20,
  },
  {
    id: "prd_tea",
    sku: "BEV-TEA-12",
    name: "Unsweetened iced tea bottles",
    category_id: "cat_beverages",
    description: "Brewed black tea, no sugar. 12-bottle case.",
    image_url: null,
    pack_size: "12 × 16oz",
    unit_count: 12,
    is_active: true,
    price_tiers: tiers(2199),
    quantity_on_hand: 18,
    low_stock_threshold: 16,
  },
  {
    id: "prd_chips",
    sku: "SNK-CHIP-50",
    name: "Tortilla chips restaurant bags",
    category_id: "cat_snacks",
    description: "White corn tortilla chips, 50 count single-serve bags.",
    image_url: null,
    pack_size: "50 × 2oz",
    unit_count: 50,
    is_active: true,
    price_tiers: tiers(3299),
    quantity_on_hand: 64,
    low_stock_threshold: 12,
  },
  {
    id: "prd_nuts",
    sku: "SNK-NUT-12",
    name: "Roasted mixed nuts",
    category_id: "cat_snacks",
    description: "Lightly salted mixed nuts in 12 bulk pouches.",
    image_url: null,
    pack_size: "12 × 16oz",
    unit_count: 12,
    is_active: true,
    price_tiers: tiers(4599),
    quantity_on_hand: 40,
    low_stock_threshold: 8,
  },
  {
    id: "prd_pretzel",
    sku: "SNK-PRET-20",
    name: "Mini pretzels",
    category_id: "cat_snacks",
    description: "Sourdough mini pretzels, 20-count case.",
    image_url: null,
    pack_size: "20 × 10oz",
    unit_count: 20,
    is_active: true,
    price_tiers: tiers(2799),
    quantity_on_hand: 0,
    low_stock_threshold: 10,
  },
  {
    id: "prd_degrease",
    sku: "CLN-DEGR-4",
    name: "Kitchen degreaser gallons",
    category_id: "cat_cleaning",
    description: "Heavy-duty degreaser for hoods and prep tables. 4-gallon case.",
    image_url: null,
    pack_size: "4 × 1 gal",
    unit_count: 4,
    is_active: true,
    price_tiers: tiers(3899),
    quantity_on_hand: 28,
    low_stock_threshold: 6,
  },
  {
    id: "prd_sanitize",
    sku: "CLN-SANI-6",
    name: "Food-surface sanitizer",
    category_id: "cat_cleaning",
    description: "No-rinse sanitizer, 6 quart bottles per case.",
    image_url: null,
    pack_size: "6 × 32oz",
    unit_count: 6,
    is_active: true,
    price_tiers: tiers(2499),
    quantity_on_hand: 8,
    low_stock_threshold: 8,
  },
  {
    id: "prd_floor",
    sku: "CLN-FLOR-4",
    name: "Neutral floor cleaner",
    category_id: "cat_cleaning",
    description: "Low-foam cleaner for quarry tile and vinyl.",
    image_url: null,
    pack_size: "4 × 1 gal",
    unit_count: 4,
    is_active: true,
    price_tiers: tiers(2199),
    quantity_on_hand: 52,
    low_stock_threshold: 8,
  },
  {
    id: "prd_towels",
    sku: "PAP-TOWL-6",
    name: "Rolled paper towels",
    category_id: "cat_paper",
    description: "Hardwound brown towels, 6 rolls per case.",
    image_url: null,
    pack_size: "6 rolls",
    unit_count: 6,
    is_active: true,
    price_tiers: tiers(2899),
    quantity_on_hand: 110,
    low_stock_threshold: 18,
  },
  {
    id: "prd_napkins",
    sku: "PAP-NAP-8",
    name: "Dispenser napkins",
    category_id: "cat_paper",
    description: "Interfold napkins, 8 sleeves per case.",
    image_url: null,
    pack_size: "8 × 500",
    unit_count: 4000,
    is_active: true,
    price_tiers: tiers(1999),
    quantity_on_hand: 75,
    low_stock_threshold: 20,
  },
  {
    id: "prd_tissue",
    sku: "PAP-TP-36",
    name: "2-ply bath tissue",
    category_id: "cat_paper",
    description: "Standard 2-ply rolls, 36 per case.",
    image_url: null,
    pack_size: "36 rolls",
    unit_count: 36,
    is_active: true,
    price_tiers: tiers(2499),
    quantity_on_hand: 44,
    low_stock_threshold: 12,
  },
  {
    id: "prd_fries",
    sku: "FRZ-FRY-6",
    name: "Straight-cut fries",
    category_id: "cat_frozen",
    description: "3/8-inch fries, six 5lb bags.",
    image_url: null,
    pack_size: "6 × 5lb",
    unit_count: 6,
    is_active: true,
    price_tiers: tiers(3299),
    quantity_on_hand: 36,
    low_stock_threshold: 10,
  },
  {
    id: "prd_tenders",
    sku: "FRZ-TEND-2",
    name: "Breaded chicken tenders",
    category_id: "cat_frozen",
    description: "Fully cooked tenders, two 10lb bags.",
    image_url: null,
    pack_size: "2 × 10lb",
    unit_count: 2,
    is_active: true,
    price_tiers: tiers(5499),
    quantity_on_hand: 4,
    low_stock_threshold: 6,
  },
  {
    id: "prd_cheese",
    sku: "DAI-CHED-4",
    name: "Shredded cheddar",
    category_id: "cat_dairy",
    description: "Feather-shred cheddar, four 5lb bags.",
    image_url: null,
    pack_size: "4 × 5lb",
    unit_count: 4,
    is_active: true,
    price_tiers: tiers(4299),
    quantity_on_hand: 22,
    low_stock_threshold: 6,
  },
  {
    id: "prd_butter",
    sku: "DAI-BUTT-36",
    name: "Salted butter prints",
    category_id: "cat_dairy",
    description: "Grade AA salted butter, 36 one-pound prints.",
    image_url: null,
    pack_size: "36 × 1lb",
    unit_count: 36,
    is_active: true,
    price_tiers: tiers(6199),
    quantity_on_hand: 15,
    low_stock_threshold: 8,
  },
  {
    id: "prd_rice",
    sku: "DRY-RICE-50",
    name: "Long-grain rice",
    category_id: "cat_dry-goods",
    description: "Parboiled long-grain rice, 50lb bag (sold as 1 case).",
    image_url: null,
    pack_size: "50lb",
    unit_count: 1,
    is_active: true,
    price_tiers: tiers(3499),
    quantity_on_hand: 80,
    low_stock_threshold: 10,
  },
  {
    id: "prd_pasta",
    sku: "DRY-PASTA-20",
    name: "Penne pasta",
    category_id: "cat_dry-goods",
    description: "Dry penne, 20 one-pound boxes.",
    image_url: null,
    pack_size: "20 × 1lb",
    unit_count: 20,
    is_active: true,
    price_tiers: tiers(2399),
    quantity_on_hand: 58,
    low_stock_threshold: 12,
  },
  {
    id: "prd_flour",
    sku: "DRY-FLR-50",
    name: "All-purpose flour",
    category_id: "cat_dry-goods",
    description: "Bleached AP flour, 50lb bag.",
    image_url: null,
    pack_size: "50lb",
    unit_count: 1,
    is_active: true,
    price_tiers: tiers(2799),
    quantity_on_hand: 33,
    low_stock_threshold: 8,
  },
  {
    id: "prd_clamshell",
    sku: "PKG-CLAM-200",
    name: "Hinged clamshell containers",
    category_id: "cat_packaging",
    description: "9-inch black hinged containers, 200 per case.",
    image_url: null,
    pack_size: "200 ct",
    unit_count: 200,
    is_active: true,
    price_tiers: tiers(3699),
    quantity_on_hand: 47,
    low_stock_threshold: 15,
  },
  {
    id: "prd_bags",
    sku: "PKG-BAG-500",
    name: "T-shirt carry bags",
    category_id: "cat_packaging",
    description: "White plastic T-shirt bags, 500 per case.",
    image_url: null,
    pack_size: "500 ct",
    unit_count: 500,
    is_active: true,
    price_tiers: tiers(1899),
    quantity_on_hand: 90,
    low_stock_threshold: 20,
  },
  {
    id: "prd_tomato",
    sku: "PRD-TOM-25",
    name: "Roma tomatoes",
    category_id: "cat_produce",
    description: "25lb case of ripe romas for sauce and slicing.",
    image_url: null,
    pack_size: "25lb",
    unit_count: 1,
    is_active: true,
    price_tiers: tiers(2299),
    quantity_on_hand: 26,
    low_stock_threshold: 10,
  },
  {
    id: "prd_onion",
    sku: "PRD-ONI-50",
    name: "Yellow onions",
    category_id: "cat_produce",
    description: "50lb bag of yellow onions.",
    image_url: null,
    pack_size: "50lb",
    unit_count: 1,
    is_active: true,
    price_tiers: tiers(1899),
    quantity_on_hand: 19,
    low_stock_threshold: 8,
  },
  {
    id: "prd_coffee",
    sku: "COF-DRIP-5",
    name: "House drip coffee",
    category_id: "cat_coffee",
    description: "Medium roast ground coffee, five 5lb bags.",
    image_url: null,
    pack_size: "5 × 5lb",
    unit_count: 5,
    is_active: true,
    price_tiers: tiers(6799),
    quantity_on_hand: 21,
    low_stock_threshold: 5,
  },
  {
    id: "prd_tea_bulk",
    sku: "COF-TEA-6",
    name: "Black tea bags bulk",
    category_id: "cat_coffee",
    description: "1000-count tea bags, 6 boxes per case.",
    image_url: null,
    pack_size: "6 × 1000",
    unit_count: 6000,
    is_active: true,
    price_tiers: tiers(4199),
    quantity_on_hand: 14,
    low_stock_threshold: 4,
  },
];
