import type { Category, Product } from "@/types/commerce";

function tiers(baseCents: number) {
  return [
    { min_cases: 1, price_per_case_cents: baseCents },
    { min_cases: 5, price_per_case_cents: Math.round(baseCents * 0.93) },
    { min_cases: 12, price_per_case_cents: Math.round(baseCents * 0.86) },
  ];
}

export const CATEGORIES: Category[] = [
  {
    id: "cat_aluminum-trays-foil",
    slug: "aluminum-trays-foil",
    name: "Aluminum trays & foil",
    description: "Steam-table pans, foil rolls, and lids.",
  },
  {
    id: "cat_plastic-containers",
    slug: "plastic-containers",
    name: "Plastic containers",
    description: "Deli cups, hinged packs, and portion cups.",
  },
  {
    id: "cat_paper-products",
    slug: "paper-products",
    name: "Paper products",
    description: "Napkins, towels, and food wrap.",
  },
  {
    id: "cat_cups-lids",
    slug: "cups-lids",
    name: "Cups & lids",
    description: "Hot cups, cold cups, and matching lids.",
  },
  {
    id: "cat_takeout-containers",
    slug: "takeout-containers",
    name: "Takeout containers",
    description: "Clamshells, boxes, and to-go trays.",
  },
  {
    id: "cat_catering-supplies",
    slug: "catering-supplies",
    name: "Catering supplies",
    description: "Chafers, serving ware, and event packs.",
  },
  {
    id: "cat_disposable-cutlery",
    slug: "disposable-cutlery",
    name: "Disposable cutlery",
    description: "Forks, knives, spoons, and kits.",
  },
  {
    id: "cat_cleaning-supplies",
    slug: "cleaning-supplies",
    name: "Cleaning supplies",
    description: "Degreasers, sanitizers, and floor care.",
  },
  {
    id: "cat_gloves-safety",
    slug: "gloves-safety",
    name: "Gloves & safety",
    description: "Foodservice gloves and safety gear.",
  },
  {
    id: "cat_bags-packaging",
    slug: "bags-packaging",
    name: "Bags & packaging",
    description: "Carry bags, liners, and wrap film.",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "prd_steam_half",
    sku: "ALU-HALF-100",
    name: "Half-size aluminum steam pans",
    category_id: "cat_aluminum-trays-foil",
    description: "Disposable half-size deep steam-table pans, 100 per case.",
    image_url: null,
    pack_size: "100 ct",
    unit_count: 100,
    is_active: true,
    price_tiers: tiers(4299),
    quantity_on_hand: 48,
    low_stock_threshold: 12,
  },
  {
    id: "prd_foil_roll",
    sku: "ALU-FOIL-18",
    name: "Heavy-duty aluminum foil roll",
    category_id: "cat_aluminum-trays-foil",
    description: "18-inch cutter-box foil, six 500ft rolls.",
    image_url: null,
    pack_size: "6 × 500ft",
    unit_count: 6,
    is_active: true,
    price_tiers: tiers(5499),
    quantity_on_hand: 31,
    low_stock_threshold: 8,
  },
  {
    id: "prd_foil_lids",
    sku: "ALU-LID-100",
    name: "Aluminum steam-pan lids",
    category_id: "cat_aluminum-trays-foil",
    description: "Domed foil lids for half-size pans, 100 per case.",
    image_url: null,
    pack_size: "100 ct",
    unit_count: 100,
    is_active: true,
    price_tiers: tiers(2899),
    quantity_on_hand: 22,
    low_stock_threshold: 10,
  },
  {
    id: "prd_deli_32",
    sku: "PLS-DELI-32",
    name: "32oz deli containers",
    category_id: "cat_plastic-containers",
    description: "Clear round deli cups with lids, 240 per case.",
    image_url: null,
    pack_size: "240 ct",
    unit_count: 240,
    is_active: true,
    price_tiers: tiers(3699),
    quantity_on_hand: 64,
    low_stock_threshold: 15,
  },
  {
    id: "prd_portion_2",
    sku: "PLS-CUP-2",
    name: "2oz portion cups",
    category_id: "cat_plastic-containers",
    description: "Souffle cups with snap lids, 2500 per case.",
    image_url: null,
    pack_size: "2500 ct",
    unit_count: 2500,
    is_active: true,
    price_tiers: tiers(2499),
    quantity_on_hand: 80,
    low_stock_threshold: 20,
  },
  {
    id: "prd_hinged_9",
    sku: "PLS-HNG-9",
    name: "9-inch hinged plastic packs",
    category_id: "cat_plastic-containers",
    description: "Clear 3-compartment hinged containers, 200 per case.",
    image_url: null,
    pack_size: "200 ct",
    unit_count: 200,
    is_active: true,
    price_tiers: tiers(4199),
    quantity_on_hand: 3,
    low_stock_threshold: 12,
  },
  {
    id: "prd_napkins",
    sku: "PAP-NAP-8",
    name: "Dispenser napkins",
    category_id: "cat_paper-products",
    description: "Interfold napkins, 8 sleeves per case.",
    image_url: null,
    pack_size: "8 × 500",
    unit_count: 4000,
    is_active: true,
    price_tiers: tiers(1999),
    quantity_on_hand: 75,
    low_stock_threshold: 20,
  },
  {
    id: "prd_towels",
    sku: "PAP-TWL-6",
    name: "Hardwound paper towels",
    category_id: "cat_paper-products",
    description: "Natural roll towels, 6 rolls per case.",
    image_url: null,
    pack_size: "6 × 800ft",
    unit_count: 6,
    is_active: true,
    price_tiers: tiers(3299),
    quantity_on_hand: 41,
    low_stock_threshold: 10,
  },
  {
    id: "prd_deli_paper",
    sku: "PAP-DELI-10",
    name: "Dry wax deli sheets",
    category_id: "cat_paper-products",
    description: "12×12 dry-wax sheets, 10 packs of 500.",
    image_url: null,
    pack_size: "10 × 500",
    unit_count: 5000,
    is_active: true,
    price_tiers: tiers(2799),
    quantity_on_hand: 36,
    low_stock_threshold: 8,
  },
  {
    id: "prd_hot_cup",
    sku: "CUP-HOT-16",
    name: "16oz hot cups",
    category_id: "cat_cups-lids",
    description: "Double-wall paper hot cups, 1000 per case.",
    image_url: null,
    pack_size: "1000 ct",
    unit_count: 1000,
    is_active: true,
    price_tiers: tiers(4599),
    quantity_on_hand: 52,
    low_stock_threshold: 14,
  },
  {
    id: "prd_cold_cup",
    sku: "CUP-CLD-24",
    name: "24oz clear cold cups",
    category_id: "cat_cups-lids",
    description: "PET cold cups, 600 per case.",
    image_url: null,
    pack_size: "600 ct",
    unit_count: 600,
    is_active: true,
    price_tiers: tiers(3899),
    quantity_on_hand: 28,
    low_stock_threshold: 10,
  },
  {
    id: "prd_lids",
    sku: "CUP-LID-16",
    name: "Travel lids for 16oz hot cups",
    category_id: "cat_cups-lids",
    description: "White sip lids, 1000 per case.",
    image_url: null,
    pack_size: "1000 ct",
    unit_count: 1000,
    is_active: true,
    price_tiers: tiers(2299),
    quantity_on_hand: 19,
    low_stock_threshold: 16,
  },
  {
    id: "prd_clamshell",
    sku: "OUT-CLAM-200",
    name: "Hinged clamshell containers",
    category_id: "cat_takeout-containers",
    description: "9-inch black hinged containers, 200 per case.",
    image_url: null,
    pack_size: "200 ct",
    unit_count: 200,
    is_active: true,
    price_tiers: tiers(3699),
    quantity_on_hand: 47,
    low_stock_threshold: 15,
  },
  {
    id: "prd_food_box",
    sku: "OUT-BOX-250",
    name: "Fold-top food boxes",
    category_id: "cat_takeout-containers",
    description: "#8 kraft food boxes, 250 per case.",
    image_url: null,
    pack_size: "250 ct",
    unit_count: 250,
    is_active: true,
    price_tiers: tiers(3499),
    quantity_on_hand: 33,
    low_stock_threshold: 10,
  },
  {
    id: "prd_noodle_box",
    sku: "OUT-NDL-200",
    name: "Paper noodle boxes",
    category_id: "cat_takeout-containers",
    description: "26oz leak-resistant noodle boxes, 200 per case.",
    image_url: null,
    pack_size: "200 ct",
    unit_count: 200,
    is_active: true,
    price_tiers: tiers(3999),
    quantity_on_hand: 0,
    low_stock_threshold: 8,
  },
  {
    id: "prd_chafer",
    sku: "CAT-CHF-4",
    name: "Full-size chafer fuel",
    category_id: "cat_catering-supplies",
    description: "2-hour wick fuel cans, 24 per case.",
    image_url: null,
    pack_size: "24 ct",
    unit_count: 24,
    is_active: true,
    price_tiers: tiers(4299),
    quantity_on_hand: 26,
    low_stock_threshold: 8,
  },
  {
    id: "prd_serving",
    sku: "CAT-SRV-50",
    name: "Clear serving tongs",
    category_id: "cat_catering-supplies",
    description: "9-inch disposable serving tongs, 50 per case.",
    image_url: null,
    pack_size: "50 ct",
    unit_count: 50,
    is_active: true,
    price_tiers: tiers(1899),
    quantity_on_hand: 18,
    low_stock_threshold: 6,
  },
  {
    id: "prd_platter",
    sku: "CAT-PLT-25",
    name: "Oval catering platters",
    category_id: "cat_catering-supplies",
    description: "16-inch black oval platters with lids, 25 per case.",
    image_url: null,
    pack_size: "25 ct",
    unit_count: 25,
    is_active: true,
    price_tiers: tiers(4799),
    quantity_on_hand: 14,
    low_stock_threshold: 5,
  },
  {
    id: "prd_forks",
    sku: "CUT-FRK-1000",
    name: "Heavyweight plastic forks",
    category_id: "cat_disposable-cutlery",
    description: "Black polypropylene forks, 1000 per case.",
    image_url: null,
    pack_size: "1000 ct",
    unit_count: 1000,
    is_active: true,
    price_tiers: tiers(2199),
    quantity_on_hand: 90,
    low_stock_threshold: 20,
  },
  {
    id: "prd_knives",
    sku: "CUT-KNF-1000",
    name: "Heavyweight plastic knives",
    category_id: "cat_disposable-cutlery",
    description: "Black polypropylene knives, 1000 per case.",
    image_url: null,
    pack_size: "1000 ct",
    unit_count: 1000,
    is_active: true,
    price_tiers: tiers(2199),
    quantity_on_hand: 84,
    low_stock_threshold: 20,
  },
  {
    id: "prd_kits",
    sku: "CUT-KIT-250",
    name: "Wrapped cutlery kits",
    category_id: "cat_disposable-cutlery",
    description: "Fork, knife, spoon, napkin, and salt/pepper, 250 kits.",
    image_url: null,
    pack_size: "250 ct",
    unit_count: 250,
    is_active: true,
    price_tiers: tiers(3299),
    quantity_on_hand: 37,
    low_stock_threshold: 10,
  },
  {
    id: "prd_degreaser",
    sku: "CLN-DEG-4",
    name: "Kitchen degreaser",
    category_id: "cat_cleaning-supplies",
    description: "Heavy-duty degreaser, four 1-gallon jugs.",
    image_url: null,
    pack_size: "4 × 1 gal",
    unit_count: 4,
    is_active: true,
    price_tiers: tiers(3899),
    quantity_on_hand: 21,
    low_stock_threshold: 6,
  },
  {
    id: "prd_sanitizer",
    sku: "CLN-SAN-4",
    name: "Quat sanitizer",
    category_id: "cat_cleaning-supplies",
    description: "No-rinse quat sanitizer, four 1-gallon jugs.",
    image_url: null,
    pack_size: "4 × 1 gal",
    unit_count: 4,
    is_active: true,
    price_tiers: tiers(3499),
    quantity_on_hand: 17,
    low_stock_threshold: 6,
  },
  {
    id: "prd_floor",
    sku: "CLN-FLR-5",
    name: "Neutral floor cleaner",
    category_id: "cat_cleaning-supplies",
    description: "Low-foam floor cleaner, five 1-gallon jugs.",
    image_url: null,
    pack_size: "5 × 1 gal",
    unit_count: 5,
    is_active: true,
    price_tiers: tiers(4199),
    quantity_on_hand: 12,
    low_stock_threshold: 5,
  },
  {
    id: "prd_nitrile",
    sku: "GLV-NIT-10",
    name: "Nitrile exam gloves",
    category_id: "cat_gloves-safety",
    description: "Powder-free nitrile, 10 boxes of 100.",
    image_url: null,
    pack_size: "10 × 100",
    unit_count: 1000,
    is_active: true,
    price_tiers: tiers(2899),
    quantity_on_hand: 55,
    low_stock_threshold: 12,
  },
  {
    id: "prd_poly_gloves",
    sku: "GLV-PLY-10",
    name: "Poly foodservice gloves",
    category_id: "cat_gloves-safety",
    description: "Embossed poly gloves, 10 dispensers of 500.",
    image_url: null,
    pack_size: "10 × 500",
    unit_count: 5000,
    is_active: true,
    price_tiers: tiers(1899),
    quantity_on_hand: 70,
    low_stock_threshold: 15,
  },
  {
    id: "prd_apron",
    sku: "GLV-APR-100",
    name: "Disposable PE aprons",
    category_id: "cat_gloves-safety",
    description: "White polyethylene aprons, 100 per case.",
    image_url: null,
    pack_size: "100 ct",
    unit_count: 100,
    is_active: true,
    price_tiers: tiers(2499),
    quantity_on_hand: 24,
    low_stock_threshold: 8,
  },
  {
    id: "prd_tshirt",
    sku: "BAG-TSH-500",
    name: "T-shirt carry bags",
    category_id: "cat_bags-packaging",
    description: "White plastic T-shirt bags, 500 per case.",
    image_url: null,
    pack_size: "500 ct",
    unit_count: 500,
    is_active: true,
    price_tiers: tiers(1899),
    quantity_on_hand: 90,
    low_stock_threshold: 20,
  },
  {
    id: "prd_liner",
    sku: "BAG-LNR-100",
    name: "33-gallon trash liners",
    category_id: "cat_bags-packaging",
    description: "Heavy black can liners, 100 per case.",
    image_url: null,
    pack_size: "100 ct",
    unit_count: 100,
    is_active: true,
    price_tiers: tiers(2799),
    quantity_on_hand: 44,
    low_stock_threshold: 10,
  },
  {
    id: "prd_film",
    sku: "BAG-FLM-4",
    name: "Foodservice stretch film",
    category_id: "cat_bags-packaging",
    description: "18-inch PVC wrap, four 2000ft rolls.",
    image_url: null,
    pack_size: "4 × 2000ft",
    unit_count: 4,
    is_active: true,
    price_tiers: tiers(4599),
    quantity_on_hand: 16,
    low_stock_threshold: 6,
  },
];
